### ISSUE TITLE
Feature Suggestion: Be able to modify the value 

### ISSUE THREAD

**Issue by jinsato0422** [GoncharukBro/react-input#12]
For the Modify Feature, it would be nice to modify the value as well.

**Comment by GoncharukBro** [comment]
Thanks for the suggestion, we are currently working on creating an easy api for users to change the value.

**Comment by GoncharukBro** [comment]
The new version adds the `track` method, with which you can conditionally change the entered value.

You can intercept input to change the entered value every time the value in the input element changes. See [Track](https://github.com/GoncharukBro/react-input/tree/main/packages/mask#track).

```
npm i @react-input/mask@latest
```
