### ISSUE TITLE
Error using custom component with required props

### ISSUE THREAD

**Issue by dfontalv20** [GoncharukBro/react-input#15]
When i try to use the `InputMask` component with a custom input, i have this error when this custom component has required props
![image](https://github.com/GoncharukBro/react-input/assets/88405607/38cbf288-3944-4153-bbe6-9c38cfd96c4f)

I think that a possible fix could be adding generic type to this `React.ComponentType`. Note the `CP` (Component Props) generic
![image](https://github.com/GoncharukBro/react-input/assets/88405607/653c7aab-b9bd-4497-9701-b36e1889e5be)

With this, the `label` prop is succesfully required in the `InputMask` component
![image](https://github.com/GoncharukBro/react-input/assets/88405607/7cadb3fe-8d0b-428f-9435-4cee452d37e4)

And if I add a value for this prop, the error dissapears
![image](https://github.com/GoncharukBro/react-input/assets/88405607/9863ae27-bd5f-4b6a-bf28-dc6a0aa2e3ca)

**Comment by GoncharukBro** [comment]
Could you please provide the complete code that reproduces the error? Some of the information is hidden on the screenshots.

**Comment by dfontalv20** [comment]
Here is a codesandbox: https://codesandbox.io/p/sandbox/priceless-dew-ty9662?file=%2Fsrc%2FApp.tsx%3A7%2C10

![image](https://github.com/GoncharukBro/react-input/assets/88405607/1543d8f3-07e4-4c43-8834-a6f1d269aa91)

**Comment by matrixmandeep** [comment]
I'm also getting the same issue.

**Comment by GoncharukBro** [comment]
Thanks for opening the topic, please update the package to the latest version, which solves this problem:

```
npm i @react-input/mask@latest
```
