### ISSUE TITLE
react-jsx-runtime.development.js bundled into dist InputMask.js

### ISSUE THREAD

**Issue by alextompkins** [GoncharukBro/react-input#17]
It is best practice to externalize all node_modules imports in a library. I can see that [you're already doing this correctly for `react`](https://github.com/GoncharukBro/react-input/blob/ff5a1d673b39f5636412135cfbb5ef9b96dca22b/utils/createRollupConfig.js#L24), but you have not externalized `react/jsx-runtime`. This means that `dist/module/InputMask.js` (and the commonjs equivalent file) ends up with the entire React jsx-runtime injected into it, [as you can see here](https://unpkg.com/@react-input/mask@1.0.20/dist/module/InputMask.js). 

This causes problems for me because I'm trying to use your package with `preact`, and I should be able to alias `react/jsx-runtime` to `preact/jsx-runtime` - but I can't if it is already inlined. It also causes unnecessary bloat in your package.

**Comment by GoncharukBro** [comment]
Thanks for opening the topic, please update the package to the latest version, which solves this problem:

```
npm i @react-input/mask@latest
```
