### ISSUE TITLE
onBeforeInput value is actual value

### ISSUE THREAD

**Issue by rickanutyi** [GoncharukBro/react-input#19]
Hi, i am using react-input/mask

`<InputMask
        ref={forwardedRef}
        mask="996(___)___-___"
        replacement="_"
        showMask
        type="number"
        {...props}
    />`
    
    The problem is, 
    
  When a user pastes a copied value, for example, 996333222111, the input value should be formatted as 996(996)333-222. I would like to have a method where I can get the value before it is processed by the mask, so I can determine if '996' is already present in the value entered by the user and remove it.
  
  I tried to use  onBeforeInput or onBeforeInputCapture? but thay give me value as 996(996)333-222

**Comment by rickanutyi** [comment]
![image](https://github.com/GoncharukBro/react-input/assets/57612014/c80666f7-d816-4fea-a01d-1ad91765c6fe)

**Comment by rickanutyi** [comment]
I just realized there is data field that has value i need.
![image](https://github.com/GoncharukBro/react-input/assets/57612014/7e0c9fd9-9727-4242-ae21-43f6e8d0f6a3)
But typescript dont know about it. And i need to change the value that way
![image](https://github.com/GoncharukBro/react-input/assets/57612014/b5a84845-d08d-4989-aab2-0f891680cc62)
I dont think it right way to work with react

**Comment by GoncharukBro** [comment]
We are currently working on being able to change the value before masking the input, we will include this feature in the next release.

**Comment by GoncharukBro** [comment]
The new version adds the `track` method, with which you can conditionally change the entered value.

You can intercept input to change the entered value every time the value in the input element changes. See [Track](https://github.com/GoncharukBro/react-input/tree/main/packages/mask#track).

```
npm i @react-input/mask@latest
```
