### ISSUE TITLE
Confusing documentation for onMask property.

### ISSUE THREAD

**Issue by mrbinky3000** [GoncharukBro/react-input#25]
The documentation for the onMask prop states  "The input-mask event is fired asynchronously after the change event".  How can something be both asynchronous and synchronous at the same time?   How do you know it is fired "after the change event" if the event is asynchronous?  Some clarification is needed.

**Comment by GoncharukBro** [comment]
This means that the event is queued for launch; the launch is initiated by the package itself. We never write information in documentation that we are not sure of.
