### ISSUE TITLE
Setting showMask to true, does not initially show the mask until you enter a character

### ISSUE THREAD

**Issue by sdancer75** [GoncharukBro/react-input#28]
Setting **showMask** to true does not initially show the mask until you enter a character

version 1.2.5 @react-input/mask
MUI 5 / React

Initial Rendering
![image](https://github.com/GoncharukBro/react-input/assets/10809692/929bf6f4-cdc0-4347-8a64-dcd416f06af0)

After entering the 1st character
![image](https://github.com/GoncharukBro/react-input/assets/10809692/baafc49f-6c2e-4e2b-abb2-14b62d110bc6)

I expected to see that with the initial rendering
![image](https://github.com/GoncharukBro/react-input/assets/10809692/5fbea907-0b29-43ae-b05b-96c7bc0dc51c)

**Comment by sdancer75** [comment]
Initialization error from my side.

**Comment by UmutKDev** [comment]
@sdancer75  how did you fixed?

**Comment by sdancer75** [comment]
> showMask



```
              
export default function RHFTextFieldMask({ name, mask, showMask = false, replacement, helperText, type, ...other }) {
   const { control } = useFormContext();

   const inputRef = useMask({ showMask, mask, replacement });
   return (
      <Controller
         name={name}
         control={control}
         render={({ field, fieldState: { error } }) => (
            <TextField
               inputRef={inputRef}
               fullWidth
               type={type}
               value={field.value}
               onChange={(event) => {
                  field.onChange(event.target.value);
               }}
               error={!!error}
               helperText={error ? error?.message : helperText}
               {...other}
            />
         )}
      />
   );
}              
              
            .......  
              
               <RHFTextFieldMask
                  required
                  name="number"
                  label="SFI code ID"
                  size="small"
                  showMask
                  mask=`${number}.___`
                  replacement={{ _: /\d/ }}
               />
```

**Comment by svetlanapuro** [comment]
Hi there,

I'm having the same error. The mask appears only when you start typing. I'm using it with Ant Design Input, here is my codesandbox https://codesandbox.io/p/sandbox/nervous-shirley-zc5fml. How can I fix it?

Also when you delete the characters and leave the field, the mask remains visible. I guess it should be hidden (with no value and onMouseLeave).
